add new component from lms
smartsystemkmplus/smartsystem-storybook pull request #2
Opened 2023-10-01 01:41 UTC by alvyfz

2023-10-02 09:44 UTC, mugeki requested changes
add `index.tsx` file yang isinya mengexport setiap component

2023-10-02 09:44 UTC, mugeki commented on src/stories/sectionModal.stories.tsx
rename to `SectionModal.stories.tsx`

2023-10-02 09:44 UTC, mugeki commented on yarn.lock
add `yarn.lock` to `.gitignore`

2023-10-03 00:23 UTC, alvyfz commented on yarn.lock
done

2023-10-03 00:23 UTC, alvyfz commented on src/stories/sectionModal.stories.tsx
done

2023-10-03 02:02 UTC, mugeki approved these changes
LGTM

2023-10-03 02:03 UTC, merged